-- All business tables live in an isolated namespace; migrations are explicitly applied.
BEGIN;
CREATE SCHEMA IF NOT EXISTS data_agent;
CREATE TABLE IF NOT EXISTS data_agent.schema_versions(version integer PRIMARY KEY, installed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS data_agent.projects(id text PRIMARY KEY, name text NOT NULL);
CREATE TABLE IF NOT EXISTS data_agent.members(project_id text REFERENCES data_agent.projects(id), actor_id text, role text NOT NULL CHECK(role IN ('owner','editor','viewer')), PRIMARY KEY(project_id,actor_id));
CREATE TABLE IF NOT EXISTS data_agent.workflows(project_id text REFERENCES data_agent.projects(id), id text, revision integer NOT NULL CHECK(revision>0), body jsonb NOT NULL, digest text NOT NULL, PRIMARY KEY(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.workflow_versions(project_id text, workflow_id text, revision integer, body jsonb NOT NULL, digest text NOT NULL, PRIMARY KEY(project_id,workflow_id,revision), FOREIGN KEY(project_id,workflow_id) REFERENCES data_agent.workflows(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.approvals(id text PRIMARY KEY, project_id text REFERENCES data_agent.projects(id), actor_id text NOT NULL, semantic_digest text NOT NULL, max_removed_fraction double precision NOT NULL CHECK(max_removed_fraction BETWEEN 0 AND 1), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,actor_id,semantic_digest,max_removed_fraction));
CREATE TABLE IF NOT EXISTS data_agent.runs(id text PRIMARY KEY, project_id text NOT NULL REFERENCES data_agent.projects(id), session_id text NOT NULL, actor_id text NOT NULL, idempotency_key text NOT NULL, request_digest text NOT NULL, snapshot jsonb NOT NULL, status text NOT NULL CHECK(status IN ('queued','running','waiting_approval','cancel_requested','cancelled','succeeded','failed')), cursor bigint NOT NULL DEFAULT 0, max_removed_fraction double precision NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,actor_id,idempotency_key), UNIQUE(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.jobs(id text PRIMARY KEY, run_id text NOT NULL REFERENCES data_agent.runs(id), node_id text NOT NULL, spec jsonb NOT NULL, status text NOT NULL CHECK(status IN ('pending','queued','running','computed_waiting_approval','cancel_requested','cancelled','succeeded','failed')), attempt_no integer NOT NULL DEFAULT 0, fencing_token bigint NOT NULL DEFAULT 0, owner text, lease_until timestamptz, progress jsonb, error_code text, UNIQUE(run_id,node_id));
CREATE INDEX IF NOT EXISTS jobs_queue ON data_agent.jobs(status,run_id);
CREATE TABLE IF NOT EXISTS data_agent.attempts(job_id text REFERENCES data_agent.jobs(id), attempt_no integer, fencing_token bigint NOT NULL, owner text NOT NULL, status text NOT NULL, manifest_digest text, manifest jsonb, receipt jsonb, PRIMARY KEY(job_id,attempt_no));
CREATE TABLE IF NOT EXISTS data_agent.artifacts(id text PRIMARY KEY, project_id text NOT NULL REFERENCES data_agent.projects(id), run_id text, job_id text REFERENCES data_agent.jobs(id), output_port text, kind text NOT NULL CHECK(kind IN ('DatasetRef','TransformerRef','ReportRef','SplitMapRef')), digest text NOT NULL, object_key text NOT NULL, bytes bigint NOT NULL CHECK(bytes>=0), metadata jsonb NOT NULL, archived boolean NOT NULL DEFAULT false, UNIQUE(job_id,output_port), UNIQUE(project_id,id), FOREIGN KEY(project_id,run_id) REFERENCES data_agent.runs(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.events(run_id text REFERENCES data_agent.runs(id), cursor bigint, body jsonb NOT NULL, delivered_at timestamptz, PRIMARY KEY(run_id,cursor));
CREATE TABLE IF NOT EXISTS data_agent.audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, project_id text NOT NULL, actor_id text NOT NULL, action text NOT NULL, body jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO data_agent.schema_versions(version) VALUES(1) ON CONFLICT DO NOTHING;
COMMIT;
