BEGIN;
CREATE TABLE IF NOT EXISTS data_agent.skill_definitions(project_id text REFERENCES data_agent.projects(id),id text,revision integer NOT NULL,draft jsonb NOT NULL,default_version text,PRIMARY KEY(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.skill_versions(project_id text,skill_id text,version text,digest text NOT NULL,snapshot jsonb NOT NULL,status text NOT NULL CHECK(status IN ('candidate','released','retired')),parent_version text,reason text NOT NULL,actor_id text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(project_id,skill_id,version),FOREIGN KEY(project_id,skill_id) REFERENCES data_agent.skill_definitions(project_id,id));
CREATE TABLE IF NOT EXISTS data_agent.skill_evaluations(id text PRIMARY KEY,project_id text,skill_id text,version text,digest text NOT NULL,suite_digest text NOT NULL,runtime_digest text NOT NULL,status text NOT NULL CHECK(status IN ('running','passed','failed')),report jsonb,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(project_id,skill_id,version) REFERENCES data_agent.skill_versions(project_id,skill_id,version));
CREATE TABLE IF NOT EXISTS data_agent.skill_releases(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,project_id text,skill_id text,version text,action text NOT NULL,evaluation_id text REFERENCES data_agent.skill_evaluations(id),actor_id text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(project_id,skill_id,version) REFERENCES data_agent.skill_versions(project_id,skill_id,version));
CREATE TABLE IF NOT EXISTS data_agent.skill_invocations(id text PRIMARY KEY,project_id text,skill_id text,version text,digest text NOT NULL,actor_id text NOT NULL,session_id text NOT NULL,input jsonb NOT NULL,runtime jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(project_id,skill_id,version) REFERENCES data_agent.skill_versions(project_id,skill_id,version));
CREATE TABLE IF NOT EXISTS data_agent.skill_feedback(id text PRIMARY KEY,invocation_id text NOT NULL REFERENCES data_agent.skill_invocations(id),actor_id text NOT NULL,body jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO data_agent.schema_versions(version) VALUES(4) ON CONFLICT DO NOTHING;
COMMIT;
